# Generated by Django 6.0.4 on 2026-06-01 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('aufgabe', 'Neue Aufgabe'), ('deadline', 'Deadline nähert sich'), ('projekt', 'Projekt-Update'), ('system', 'System-Mitteilung')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notify_projekt', models.BooleanField(default=False)),
                ('notify_deadline', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projekt_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_bild', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('avatar_farbe', models.CharField(default='#3b82f6', max_length=20)),
                ('profil_oeffentlich', models.BooleanField(default=True)),
                ('in_teilnehmerliste_auffindbar', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_system', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('kompakt_modus', models.BooleanField(default=False)),
                ('sprache', models.CharField(default='de', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True)),
                ('fortschritt', models.IntegerField(default=0)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('projekte_oeffentlich', models.BooleanField(default=False)),
                ('nur_mitgliederzugriff', models.BooleanField(default=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_projekte', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mitgliedschaft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beigetreten_am', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitgliedschaften', to=settings.AUTH_USER_MODEL)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitgliedschaft_set', to='projekte.projekt')),
            ],
            options={
                'unique_together': {('user', 'projekt')},
            },
        ),
    ]
