# Generated by Django 6.0.4 on 2026-05-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mitgliedschaft',
            old_name='ussr',
            new_name='user',
        ),
    ]
