# Generated by Django 6.0.4 on 2026-05-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekte', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dark_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='kompakt_modus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_system',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sprache',
            field=models.CharField(default='de', max_length=10),
        ),
    ]
