# Generated by Django 6.0.4 on 2026-05-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekte', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='fortschritt',
        ),
    ]
