# Generated by Django 6.0.4 on 2026-05-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekte', '0008_remove_project_fortschritt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='in_teilnehmerliste_auffindbar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profil_oeffentlich',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='nur_mitgliederzugriff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='projekte_oeffentlich',
            field=models.BooleanField(default=False),
        ),
    ]
