# Generated by Django 6.0.4 on 2026-05-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekte', '0009_profile_in_teilnehmerliste_auffindbar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notify_deadline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='notify_projekt',
            field=models.BooleanField(default=False),
        ),
    ]
