# Generated by Django 6.0.4 on 2026-06-04 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projekte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatNachricht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nachrichten', to='projekte.projekt')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gesendete_nachrichten', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['erstellt_am'],
            },
        ),
    ]
