# Generated by Django 6.0.4 on 2026-05-28 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aufgaben', '0001_initial'),
        ('projekte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe',
            name='prioritaet',
            field=models.CharField(choices=[('niedrig', 'Niedrig'), ('mittel', 'Mittel'), ('hoch', 'Hoch')], default='mittel', max_length=20),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='projekt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aufgaben', to='projekte.projekt'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='status',
            field=models.CharField(choices=[('offen', 'Offen'), ('in_bearbeitung', 'In Bearbeitung'), ('in_ueberpruefung', 'In Überprüfung'), ('erledigt', 'Erledigt')], default='offen', max_length=30),
        ),
        migrations.CreateModel(
            name='ChatNachricht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('empfaenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erhaltene_chat_nachrichten', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gesendete_chat_nachrichten', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='Kommentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kommentare', to='aufgaben.aufgabe')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['erstellt_am'],
            },
        ),
    ]
