# Generated by Django 6.0.4 on 2026-05-26 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aufgaben', '0002_chatnachricht'),
        ('projekte', '0008_remove_project_fortschritt'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='projekt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aufgaben', to='projekte.project'),
        ),
    ]
